backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: j-meech/aly-dalrymple
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Work"
    name: "work"
    folder: "src/work"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - label: "Size"
        name: "size"
        widget: "string"
        required: false
        hint: "ie. 500mm x 300mm"
      - label: "Featured"
        name: "featured"
        widget: "boolean"
        default: false
        required: false
        hint: "If set will show on featured work section on homepage page, probably best to limit this to just a few."
      - label: "Display Order"
        name: "displayOrder"
        widget: "number"
        value_type: "int"
        min: 1
        max: 101
        required: false
        hint: "If you've selected featured this will decide the order they are displayed."
      - label: "Commission"
        name: "commission"
        widget: "boolean"
        default: false
        required: false
        hint: "If set will show on commissions page"
      - widget: select
        label: "Tags"
        name: "tags"
        multiple: true
        create: true
        required: false
        options: ["birds", "portrait", "commission", "lanscape", "abstract"]
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Thumbnail Image"
        name: "thumbnail"
        widget: "image"
        required: false
        allow_multiple: false
      - label: "Main Image"
        name: "mainImage"
        widget: "image"
        required: false
        allow_multiple: false
      - label: "Gallery"
        name: "gallery"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: true
